default: &default
  command_execute:
    url:  'localhost:4567/execute'
    auth: 'rails_user:rails_pass'

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default
  
  command_execute:
    url: <%= ENV['COMMAND_EXECUTE_URL'] %>
