default: &default
  command_execute_url:  'localhost:4567/execute'
  command_execute_auth: 'rails_user:rails_pass'

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default  
  command_execute_url: <%= ENV['COMMAND_EXECUTE_URL'] %>
